"""Seed initial sources into the database.

Usage:
    docker-compose exec backend python -m app.scripts.seed_sources
"""

import asyncio
import logging

from sqlalchemy import select

from app.database import async_session_maker
from app.models.source import Source

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

INITIAL_SOURCES = [
    {
        "name": "GitHub Changelog",
        "source_type": "rss",
        "feed_url": "https://github.blog/changelog/feed/",
        "trust_tier": "very_high",
        "topics": ["Technology", "Software Process", "AI"],
        "status": "active",
        "target_roles": ["Engineering", "DevOps"],
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "OpenAI Blog",
        "source_type": "rss",
        "feed_url": "https://openai.com/blog/rss.xml",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Executive", "Engineering", "Data/AI"],
        "config": {"max_items": 20, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "Microsoft AI Blog",
        "source_type": "rss",
        "feed_url": "https://blogs.microsoft.com/ai/feed/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "target_roles": ["Executive", "Engineering", "Data/AI"],
        "config": {"max_items": 20, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "Google AI Blog",
        "source_type": "rss",
        "feed_url": "https://blog.google/technology/ai/rss/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 20, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "Google DeepMind",
        "source_type": "rss",
        "feed_url": "https://deepmind.google/blog/rss.xml",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 20, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "AWS What's New",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
        "trust_tier": "very_high",
        "topics": ["Dịch vụ/Nền tảng"],
        "status": "active",
        "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "AWS ML Blog",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/blogs/machine-learning/feed/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "NVIDIA Blog",
        "source_type": "rss",
        "feed_url": "https://blogs.nvidia.com/feed/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "target_roles": ["Data/AI", "Infrastructure", "Engineering"],
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Cloudflare Blog",
        "source_type": "rss",
        "feed_url": "https://blog.cloudflare.com/rss/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Dịch vụ/Nền tảng"],
        "status": "active",
        "target_roles": ["Security", "Infrastructure", "DevOps"],
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "arXiv CS.AI",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.AI",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "arXiv CS.CL",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.CL",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "arXiv CS.LG",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.LG",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "IEEE Spectrum",
        "source_type": "rss",
        "feed_url": "https://spectrum.ieee.org/feeds/feed.rss",
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Engineering", "Toàn công ty"],
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Ars Technica",
        "source_type": "rss",
        "feed_url": "https://feeds.arstechnica.com/arstechnica/technology-lab",
        "trust_tier": "high",
        "topics": ["Công nghệ", "An ninh mạng"],
        "status": "active",
        "target_roles": ["Engineering", "Security"],
        "config": {"max_items": 20, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "VnExpress Số hóa",
        "source_type": "rss",
        "feed_url": "https://vnexpress.net/rss/so-hoa.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Toàn công ty", "Executive"],
        "config": {"max_items": 20, "language": "vi", "fetch_full_content": True},
    },
    {
        "name": "HackerNews",
        "source_type": "hackernews",
        "feed_url": None,
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo", "Quy trình phần mềm"],
        "status": "active",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 15, "min_score": 50, "fetch_timeout": 10},
    },
    {
        "name": "Reddit r/MachineLearning",
        "source_type": "reddit",
        "feed_url": None,
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 25, "min_upvotes": 20, "fetch_timeout": 10, "subreddit": "MachineLearning"},
    },
    {
        "name": "Reddit r/artificial",
        "source_type": "reddit",
        "feed_url": None,
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 25, "min_upvotes": 20, "fetch_timeout": 10, "subreddit": "artificial"},
    },
    # Sub-channel feeds (radar-polish-and-coverage 2026-05-09) — target_roles promoted to top-level column (w2-source-coverage)
    {
        "name": "AWS Security Blog",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/blogs/security/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Dịch vụ/Nền tảng"],
        "status": "active",
        "target_roles": ["Security", "DevOps", "Engineering"],
        "config": {
            "max_items": 15,
            "language": "en",
        },
    },
    {
        "name": "AWS Compute Blog",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/blogs/compute/feed/",
        "trust_tier": "very_high",
        "topics": ["Công nghệ", "Dịch vụ/Nền tảng"],
        "status": "active",
        "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        "config": {
            "max_items": 15,
            "language": "en",
        },
    },
    {
        "name": "arXiv CS.IR",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.IR",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {
            "max_items": 10,
            "language": "en",
        },
    },
    {
        "name": "arXiv CS.SE",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.SE",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm"],
        "status": "inactive",
        "target_roles": ["Engineering", "BA/QA"],
        "config": {
            "max_items": 10,
            "language": "en",
        },
    },
    {
        "name": "arXiv CS.CR",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.CR",
        "trust_tier": "high",
        "topics": ["An ninh mạng"],
        "status": "inactive",
        "target_roles": ["Security", "Engineering"],
        "config": {
            "max_items": 10,
            "language": "en",
        },
    },
    # arXiv thực dụng cho Smart City/IoT — thị giác, âm thanh, robotics, HCI (w2-source-coverage 2026-07-08)
    {
        "name": "arXiv CS.CV",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.CV",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "arXiv EESS.AS",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/eess.AS",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "arXiv CS.RO",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.RO",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering", "Infrastructure"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "arXiv CS.HC",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.HC",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "target_roles": ["Designer/UX", "Product", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    # China AI sources (add-china-ai-sources 2026-05-09)
    # Note: HuggingFace org feed.xml requires auth (401) — defer to future HF Papers API connector.
    # These 5 are RSS-verified working alternatives (Substack newsletters + GitHub releases for flagship repos).
    {
        "name": "Interconnects",
        "source_type": "rss",
        "feed_url": "https://www.interconnects.ai/feed",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Cập nhật nghiên cứu"],
        "status": "active",
        "region": "china",
        "target_roles": ["Executive", "Engineering", "Data/AI"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "ChinaTalk",
        "source_type": "rss",
        "feed_url": "https://www.chinatalk.media/feed",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Thị trường/Đối thủ", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "china",
        "target_roles": ["Executive", "Engineering", "Data/AI", "Legal/Compliance"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "ChinAI Newsletter",
        "source_type": "rss",
        "feed_url": "https://chinai.substack.com/feed",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Thị trường/Đối thủ"],
        "status": "active",
        "region": "china",
        "target_roles": ["Executive", "Data/AI"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "DeepSeek V3 Releases",
        "source_type": "rss",
        "feed_url": "https://github.com/deepseek-ai/DeepSeek-V3/releases.atom",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en", "min_content_length": 0},
    },
    {
        "name": "Yi 01.AI Releases",
        "source_type": "rss",
        "feed_url": "https://github.com/01-ai/Yi/releases.atom",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en", "min_content_length": 0},
    },
    # Phase 2A: Global AI / Dev / DevOps / Security expansion (expand-source-coverage-2a 2026-05-11)
    # Note: Anthropic + Papers With Code defer — no working RSS endpoint found.
    {
        "name": "Hugging Face Blog",
        "source_type": "web_index",
        "feed_url": "https://huggingface.co/blog",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Cập nhật nghiên cứu"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {
            "link_pattern": r"/blog/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+",
            "exclude_patterns": [r"/blog/?$", r"/blog/feed"],
            "max_items": 10,
        },
    },
    {
        "name": "Stack Overflow Blog",
        "source_type": "rss",
        "feed_url": "https://stackoverflow.blog/feed/",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering"],
        "config": {"max_items": 15, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "dev.to AI",
        "source_type": "rss",
        "feed_url": "https://dev.to/feed/tag/ai",
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "dev.to ML",
        "source_type": "rss",
        "feed_url": "https://dev.to/feed/tag/machinelearning",
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "JetBrains Blog",
        "source_type": "rss",
        "feed_url": "https://blog.jetbrains.com/feed/",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "Docker Blog",
        "source_type": "rss",
        "feed_url": "https://www.docker.com/blog/feed/",
        "trust_tier": "very_high",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "Kubernetes Blog",
        "source_type": "rss",
        "feed_url": "https://kubernetes.io/feed.xml",
        "trust_tier": "very_high",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "KrebsOnSecurity",
        "source_type": "rss",
        "feed_url": "https://krebsonsecurity.com/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Legal/Compliance", "Toàn công ty"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "BleepingComputer",
        "source_type": "rss",
        "feed_url": "https://www.bleepingcomputer.com/feed/",
        "trust_tier": "high",
        "topics": ["An ninh mạng", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Engineering"],
        "config": {"max_items": 12, "language": "en", "fetch_full_content": True},
    },
    {
        "name": "Microsoft Security Blog",
        "source_type": "rss",
        "feed_url": "https://www.microsoft.com/en-us/security/blog/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Legal/Compliance", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "GitHub Security Blog",
        "source_type": "rss",
        "feed_url": "https://github.blog/security/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Engineering", "DevOps"],
        "config": {"max_items": 12, "language": "en"},
    },
    # Phase 2B: Vietnam news + community (expand-source-coverage-2b 2026-05-11)
    # Defer: CafeF, ICTNews, VietTimes, MLOpsVN, 200lab — no working RSS endpoint
    {
        "name": "GenK",
        "source_type": "rss",
        "feed_url": "https://genk.vn/rss/home.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Toàn công ty", "Engineering"],
        "config": {"max_items": 15, "language": "vi", "fetch_full_content": True},
    },
    {
        "name": "VietnamNet ICT",
        "source_type": "rss",
        "feed_url": "https://vietnamnet.vn/cong-nghe.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Toàn công ty", "Executive"],
        "config": {"max_items": 10, "language": "vi", "fetch_full_content": True},
    },
    {
        "name": "Viblo",
        "source_type": "web_index",
        "feed_url": "https://viblo.asia/newest",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering"],
        "config": {
            "link_pattern": r"/p/[a-zA-Z0-9-]+$",
            "exclude_patterns": [r"/newest/?$", r"/t/", r"/u/"],
            "max_items": 10,
        },
    },
    {
        "name": "Daynhauhoc",
        "source_type": "rss",
        "feed_url": "https://daynhauhoc.com/latest.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering"],
        "config": {"max_items": 10, "language": "vi"},
    },
    {
        "name": "Machine Learning Cơ Bản",
        "source_type": "web_index",
        "feed_url": "https://machinelearningcoban.com",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {
            "link_pattern": r"/\d{4}/\d{2}/\d{2}/",
            "exclude_patterns": [r"/page/", r"/tag/", r"/category/"],
            "max_items": 10,
        },
    },
    # GitHub Trending — early code activity signal (github-trending-connector 2026-05-11)
    {
        "name": "GitHub Trending — All Daily",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "", "since": "daily", "max_items": 25},
    },
    {
        "name": "GitHub Trending — Python Daily",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "python", "since": "daily", "max_items": 25},
    },
    {
        "name": "GitHub Trending — Weekly All",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "", "since": "weekly", "max_items": 25},
    },
    {
        "name": "GitHub Trending — Monthly All",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "", "since": "monthly", "max_items": 25},
    },
    {
        "name": "GitHub Trending — TypeScript Daily",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering"],
        "config": {"language": "typescript", "since": "daily", "max_items": 15},
    },
    # HuggingFace org models — 8 China AI labs via public HF API (unblock-coverage 2026-05-11)
    {
        "name": "HF DeepSeek",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "deepseek-ai", "max_items": 10, "min_likes": 5},
    },
    {
        "name": "HF Qwen",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "Qwen", "max_items": 10, "min_likes": 5},
    },
    {
        "name": "HF Zhipu (GLM)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "zai-org", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF 01.AI (Yi)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "01-ai", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF Moonshot (Kimi)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "moonshotai", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF Tencent (Hunyuan)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "tencent", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF MiniMax",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "MiniMaxAI", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF Baichuan",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "baichuan-inc", "max_items": 8, "min_likes": 5},
    },
    # Web index sources — scrape index pages for sites without working RSS
    {
        "name": "Anthropic News",
        "source_type": "web_index",
        "feed_url": "https://www.anthropic.com/news",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Executive", "Engineering", "Data/AI", "Legal/Compliance"],
        "config": {
            "link_pattern": r"/news/[^/]+$",
            "exclude_patterns": [r"/news/?$", r"/news/category/", r"/news/tag/"],
            "max_items": 10,
        },
    },
    {
        "name": "200lab Blog",
        "source_type": "web_index",
        "feed_url": "https://200lab.io/blog",
        "trust_tier": "high",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering", "DevOps"],
        "config": {
            "link_pattern": r"/blog/[a-z0-9-]+$",
            "exclude_patterns": [r"/blog/author/", r"/blog/tag/", r"/blog/category/", r"/blog/?$"],
            "max_items": 10,
        },
    },
    # Playwright sources — JavaScript-rendered SPA sites without RSS
    # {
    #     "name": "VietTimes Công nghệ",
    #     "source_type": "rss",
    #     "feed_url": "https://viettimes.vn/rss/khoa-hoc-cong-nghe-109.rss",
    #     "trust_tier": "medium",
    #     "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
    #     "status": "active",
    #     "region": "vietnam",
    #     "target_roles": ["Engineering", "Data/AI", "Product"],
    #     "config": {"max_items": 15, "language": "vi"},
    # },
    # {
    #     "name": "ICTNews Công nghệ",
    #     "source_type": "playwright",
    #     "feed_url": "https://ictnews.vn/cntt-vien-thong",
    #     "trust_tier": "medium",
    #     "topics": ["Công nghệ", "Trí tuệ nhân tạo", "Pháp lý/Tuân thủ"],
    #     "status": "active",
    #     "region": "vietnam",
    #     "target_roles": ["Engineering", "Data/AI", "Executive"],
    #     "config": {
    #         "link_selector": "a",
    #         "link_pattern": r"/[^/?#]+-\d+\.html$",
    #         "max_items": 10,
    #     },
    # },

    # MLOpsVN Blog — disabled: /blog returns 404 as of 2026-05-12
    {
        "name": "MLOpsVN Blog",
        "source_type": "playwright",
        "feed_url": "https://mlops.vn/blog",
        "trust_tier": "medium",
        "topics": ["Quy trình phần mềm", "Dữ liệu"],
        "status": "inactive",
        "region": "vietnam",
        "target_roles": ["Data/AI", "DevOps", "Engineering"],
        "config": {},
    },
    # Experimental Social Media Sources (Playwright/CloakBrowser benchmark)
    {
        "name": "LinkedIn - OpenAI",
        "source_type": "playwright",
        "feed_url": "https://www.linkedin.com/company/openai/posts/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {
            "link_selector": ".feed-shared-update-v2",
            "link_pattern": r"/posts/openai_",
            "wait_for": ".feed-shared-update-v2",
            "max_items": 5,
            "cookie_file": "/secrets/states/linkedin_state.json",
            "auto_scroll_count": 1,
            "extract_from_feed": True,
        },
    },
    {
        "name": "LinkedIn - Anthropic",
        "source_type": "playwright",
        # Slug `company/anthropic` là một quỹ VC/PE trùng tên (4K followers, "No posts yet") —
        # Anthropic AI thật nằm ở `anthropicresearch` (4,19M followers). Sửa 20/07/2026.
        "feed_url": "https://www.linkedin.com/company/anthropicresearch/posts/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "An ninh mạng"],
        "status": "active",
        "region": "global",
        "target_roles": ["Data/AI", "Security", "Engineering"],
        "config": {
            "link_selector": ".feed-shared-update-v2",
            "link_pattern": r"/posts/anthropicresearch_",
            "wait_for": ".feed-shared-update-v2",
            "max_items": 5,
            "cookie_file": "/secrets/states/linkedin_state.json",
            "auto_scroll_count": 1,
            "extract_from_feed": True,
        },
    },
    {
        "name": "LinkedIn - OWASP",
        "source_type": "playwright",
        "feed_url": "https://www.linkedin.com/company/owasp/posts/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Engineering"],
        "config": {
            "link_selector": ".feed-shared-update-v2",
            "link_pattern": r"/posts/owasp_",
            "wait_for": ".feed-shared-update-v2",
            "max_items": 5,
            "cookie_file": "/secrets/states/linkedin_state.json",
            "auto_scroll_count": 1,
            "extract_from_feed": True,
        },
    },
    {
        "name": "LinkedIn - Andrew Ng",
        "source_type": "playwright",
        "feed_url": "https://www.linkedin.com/in/andrewyng/recent-activity/shares/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "region": "global",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {
            "link_selector": ".feed-shared-update-v2",
            "link_pattern": r"/posts/andrewyng",
            "wait_for": ".feed-shared-update-v2",
            "max_items": 5,
            "cookie_file": "/secrets/states/linkedin_state.json",
            "auto_scroll_count": 1,
            "extract_from_feed": True,
        },
    },
    {
        "name": "DAIR.AI Top Papers",
        "source_type": "rss",
        "feed_url": "https://github.com/dair-ai/AI-Papers-of-the-Week/commits/main.atom",
        "trust_tier": "high",
        "topics": ["AI/ML Nghiên cứu", "Trí tuệ nhân tạo"],
        "status": "active",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {
            "max_items": 3,
            "language": "en",
        },
    },
    # T6 seed bù — nâng vai trò kỹ thuật mỏng lên ≥5 (w2-source-coverage 2026-07-08)
    # BA/QA (test automation, requirements) — trước đó 0 nguồn active sau khi tắt cs.SE
    {
        "name": "Google Testing Blog",
        "source_type": "rss",
        "feed_url": "https://testing.googleblog.com/feeds/posts/default",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["BA/QA", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "Postman Blog",
        "source_type": "rss",
        "feed_url": "https://blog.postman.com/feed/",
        "trust_tier": "medium",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["BA/QA", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "Applitools Blog",
        "source_type": "rss",
        "feed_url": "https://applitools.com/blog/feed/",
        "trust_tier": "medium",
        "topics": ["Quy trình phần mềm", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["BA/QA", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "Cypress Blog",
        "source_type": "rss",
        "feed_url": "https://www.cypress.io/blog/rss.xml",
        "trust_tier": "medium",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["BA/QA", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "BrowserStack Blog",
        "source_type": "rss",
        "feed_url": "https://www.browserstack.com/blog/feed/",
        "trust_tier": "medium",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["BA/QA", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    # Designer/UX — trước đó 1 nguồn (cs.HC)
    {
        "name": "Nielsen Norman Group",
        "source_type": "rss",
        "feed_url": "https://www.nngroup.com/feed/rss/",
        "trust_tier": "high",
        "topics": ["Dịch vụ/Nền tảng", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Designer/UX", "Product"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "UX Collective",
        "source_type": "rss",
        "feed_url": "https://uxdesign.cc/feed",
        "trust_tier": "medium",
        "topics": ["Dịch vụ/Nền tảng", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Designer/UX", "Product"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "Smashing Magazine",
        "source_type": "rss",
        "feed_url": "https://www.smashingmagazine.com/feed/",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Designer/UX", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "A List Apart",
        "source_type": "rss",
        "feed_url": "https://alistapart.com/main/feed/",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Designer/UX", "Engineering"],
        "config": {"max_items": 10, "language": "en"},
    },
    # Product — trước đó 2 nguồn
    {
        "name": "Lenny's Newsletter",
        "source_type": "rss",
        "feed_url": "https://www.lennysnewsletter.com/feed",
        "trust_tier": "high",
        "topics": ["Dịch vụ/Nền tảng", "Thị trường/Đối thủ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Product", "Executive"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "Silicon Valley Product Group",
        "source_type": "rss",
        "feed_url": "https://www.svpg.com/articles/feed/",
        "trust_tier": "high",
        "topics": ["Dịch vụ/Nền tảng", "Quản trị nội bộ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Product"],
        "config": {"max_items": 10, "language": "en"},
    },
    # Legal/Compliance — trước đó 4 nguồn
    {
        "name": "EFF Deeplinks",
        "source_type": "rss",
        "feed_url": "https://www.eff.org/rss/updates.xml",
        "trust_tier": "high",
        "topics": ["Pháp lý/Tuân thủ", "An ninh mạng"],
        "status": "active",
        "region": "global",
        "target_roles": ["Legal/Compliance", "Security"],
        "config": {"max_items": 10, "language": "en"},
    },
]


async def seed() -> None:
    """Insert seed sources if they don't already exist."""
    async with async_session_maker() as session:
        for data in INITIAL_SOURCES:
            result = await session.execute(
                select(Source).where(Source.name == data["name"])
            )
            existing = result.scalar_one_or_none()

            if existing:
                existing.config = data.get("config", {})
                existing.feed_url = data.get("feed_url")
                existing.trust_tier = data.get("trust_tier")
                existing.topics = data.get("topics", [])
                existing.region = data.get("region", "global")
                existing.target_roles = data.get("target_roles", [])
                existing.status = data.get("status", "active")
                session.add(existing)
                await session.commit()
                logger.info("Updated source configuration: %s", data["name"])
                continue

            source = Source(**data)
            session.add(source)
            await session.commit()
            logger.info("Created source: %s (id=%s)", source.name, source.id)

    logger.info("Seed complete.")


if __name__ == "__main__":
    asyncio.run(seed())
