"""Seed initial sources into the database.

Usage:
    docker-compose exec backend python -m app.scripts.seed_sources
"""

import asyncio
import logging

from sqlalchemy import select

from app.database import async_session_maker
from app.models.source import Source

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

INITIAL_SOURCES = [
    {
        "name": "GitHub Changelog",
        "source_type": "rss",
        "feed_url": "https://github.blog/changelog/feed/",
        "trust_tier": "very_high",
        "topics": ["Technology", "Software Process", "AI"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "OpenAI Blog",
        "source_type": "rss",
        "feed_url": "https://openai.com/blog/rss.xml",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Microsoft AI Blog",
        "source_type": "rss",
        "feed_url": "https://blogs.microsoft.com/ai/feed/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Google AI Blog",
        "source_type": "rss",
        "feed_url": "https://blog.google/technology/ai/rss/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Google DeepMind",
        "source_type": "rss",
        "feed_url": "https://deepmind.google/blog/rss.xml",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "AWS What's New",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
        "trust_tier": "very_high",
        "topics": ["Dịch vụ/Nền tảng"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "AWS ML Blog",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/blogs/machine-learning/feed/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "NVIDIA Blog",
        "source_type": "rss",
        "feed_url": "https://blogs.nvidia.com/feed/",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Cloudflare Blog",
        "source_type": "rss",
        "feed_url": "https://blog.cloudflare.com/rss/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Dịch vụ/Nền tảng"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "arXiv CS.AI",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.AI",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "arXiv CS.CL",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.CL",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "arXiv CS.LG",
        "source_type": "rss",
        "feed_url": "https://rss.arxiv.org/rss/cs.LG",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "IEEE Spectrum",
        "source_type": "rss",
        "feed_url": "https://spectrum.ieee.org/feeds/feed.rss",
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "Ars Technica",
        "source_type": "rss",
        "feed_url": "https://feeds.arstechnica.com/arstechnica/technology-lab",
        "trust_tier": "high",
        "topics": ["Công nghệ", "An ninh mạng"],
        "status": "active",
        "config": {"max_items": 20, "language": "en"},
    },
    {
        "name": "VnExpress Số hóa",
        "source_type": "rss",
        "feed_url": "https://vnexpress.net/rss/so-hoa.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "config": {"max_items": 20, "language": "vi"},
    },
    {
        "name": "HackerNews",
        "source_type": "hackernews",
        "feed_url": None,
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo", "Quy trình phần mềm"],
        "status": "active",
        "config": {"max_items": 15, "min_score": 50, "fetch_timeout": 10},
    },
    {
        "name": "Reddit r/MachineLearning",
        "source_type": "reddit",
        "feed_url": None,
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "config": {"max_items": 25, "min_upvotes": 20, "fetch_timeout": 10, "subreddit": "MachineLearning"},
    },
    {
        "name": "Reddit r/artificial",
        "source_type": "reddit",
        "feed_url": None,
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "config": {"max_items": 25, "min_upvotes": 20, "fetch_timeout": 10, "subreddit": "artificial"},
    },
    # Sub-channel feeds (radar-polish-and-coverage 2026-05-09) — target_roles in config until P1 schema lands
    {
        "name": "AWS Security Blog",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/blogs/security/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Dịch vụ/Nền tảng"],
        "status": "active",
        "config": {
            "max_items": 15,
            "language": "en",
            "target_roles": ["Security", "DevOps", "Engineering"],
        },
    },
    {
        "name": "AWS Compute Blog",
        "source_type": "rss",
        "feed_url": "https://aws.amazon.com/blogs/compute/feed/",
        "trust_tier": "very_high",
        "topics": ["Công nghệ", "Dịch vụ/Nền tảng"],
        "status": "active",
        "config": {
            "max_items": 15,
            "language": "en",
            "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        },
    },
    {
        "name": "arXiv CS.IR",
        "source_type": "rss",
        "feed_url": "https://export.arxiv.org/rss/cs.IR",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "config": {
            "max_items": 10,
            "language": "en",
            "target_roles": ["Data/AI", "Engineering"],
        },
    },
    {
        "name": "arXiv CS.SE",
        "source_type": "rss",
        "feed_url": "https://export.arxiv.org/rss/cs.SE",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm"],
        "status": "active",
        "config": {
            "max_items": 10,
            "language": "en",
            "target_roles": ["Engineering", "BA/QA"],
        },
    },
    {
        "name": "arXiv CS.CR",
        "source_type": "rss",
        "feed_url": "https://export.arxiv.org/rss/cs.CR",
        "trust_tier": "high",
        "topics": ["An ninh mạng"],
        "status": "active",
        "config": {
            "max_items": 10,
            "language": "en",
            "target_roles": ["Security", "Engineering"],
        },
    },
    # China AI sources (add-china-ai-sources 2026-05-09)
    # Note: HuggingFace org feed.xml requires auth (401) — defer to future HF Papers API connector.
    # These 5 are RSS-verified working alternatives (Substack newsletters + GitHub releases for flagship repos).
    {
        "name": "Interconnects",
        "source_type": "rss",
        "feed_url": "https://www.interconnects.ai/feed",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Cập nhật nghiên cứu"],
        "status": "active",
        "region": "china",
        "target_roles": ["Executive", "Engineering", "Data/AI"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "ChinaTalk",
        "source_type": "rss",
        "feed_url": "https://www.chinatalk.media/feed",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Thị trường/Đối thủ", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "china",
        "target_roles": ["Executive", "Engineering", "Data/AI", "Legal/Compliance"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "ChinAI Newsletter",
        "source_type": "rss",
        "feed_url": "https://chinai.substack.com/feed",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Thị trường/Đối thủ"],
        "status": "active",
        "region": "china",
        "target_roles": ["Executive", "Data/AI"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "DeepSeek V3 Releases",
        "source_type": "rss",
        "feed_url": "https://github.com/deepseek-ai/DeepSeek-V3/releases.atom",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "Yi 01.AI Releases",
        "source_type": "rss",
        "feed_url": "https://github.com/01-ai/Yi/releases.atom",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    # Phase 2A: Global AI / Dev / DevOps / Security expansion (expand-source-coverage-2a 2026-05-11)
    # Note: Anthropic + Papers With Code defer — no working RSS endpoint found.
    {
        "name": "Hugging Face Blog",
        "source_type": "web_index",
        "feed_url": "https://huggingface.co/blog",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Cập nhật nghiên cứu"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {
            "link_pattern": r"/blog/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+",
            "exclude_patterns": [r"/blog/?$", r"/blog/feed"],
            "max_items": 10,
        },
    },
    {
        "name": "Stack Overflow Blog",
        "source_type": "rss",
        "feed_url": "https://stackoverflow.blog/feed/",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering"],
        "config": {"max_items": 15, "language": "en"},
    },
    {
        "name": "dev.to AI",
        "source_type": "rss",
        "feed_url": "https://dev.to/feed/tag/ai",
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "dev.to ML",
        "source_type": "rss",
        "feed_url": "https://dev.to/feed/tag/machinelearning",
        "trust_tier": "medium",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"max_items": 10, "language": "en"},
    },
    {
        "name": "JetBrains Blog",
        "source_type": "rss",
        "feed_url": "https://blog.jetbrains.com/feed/",
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "Docker Blog",
        "source_type": "rss",
        "feed_url": "https://www.docker.com/blog/feed/",
        "trust_tier": "very_high",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "Kubernetes Blog",
        "source_type": "rss",
        "feed_url": "https://kubernetes.io/feed.xml",
        "trust_tier": "very_high",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["DevOps", "Infrastructure", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "KrebsOnSecurity",
        "source_type": "rss",
        "feed_url": "https://krebsonsecurity.com/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Legal/Compliance", "Toàn công ty"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "BleepingComputer",
        "source_type": "rss",
        "feed_url": "https://www.bleepingcomputer.com/feed/",
        "trust_tier": "high",
        "topics": ["An ninh mạng", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "Microsoft Security Blog",
        "source_type": "rss",
        "feed_url": "https://www.microsoft.com/en-us/security/blog/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Legal/Compliance", "Engineering"],
        "config": {"max_items": 12, "language": "en"},
    },
    {
        "name": "GitHub Security Blog",
        "source_type": "rss",
        "feed_url": "https://github.blog/security/feed/",
        "trust_tier": "very_high",
        "topics": ["An ninh mạng", "Quy trình phần mềm"],
        "status": "active",
        "region": "global",
        "target_roles": ["Security", "Engineering", "DevOps"],
        "config": {"max_items": 12, "language": "en"},
    },
    # Phase 2B: Vietnam news + community (expand-source-coverage-2b 2026-05-11)
    # Defer: CafeF, ICTNews, VietTimes, MLOpsVN, 200lab — no working RSS endpoint
    {
        "name": "GenK",
        "source_type": "rss",
        "feed_url": "https://genk.vn/rss/home.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Toàn công ty", "Engineering"],
        "config": {"max_items": 15, "language": "vi"},
    },
    {
        "name": "VietnamNet ICT",
        "source_type": "rss",
        "feed_url": "https://vietnamnet.vn/cong-nghe.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Toàn công ty", "Executive"],
        "config": {"max_items": 10, "language": "vi"},
    },
    {
        "name": "Viblo",
        "source_type": "web_index",
        "feed_url": "https://viblo.asia/newest",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering"],
        "config": {
            "link_pattern": r"/p/[a-zA-Z0-9-]+$",
            "exclude_patterns": [r"/newest/?$", r"/t/", r"/u/"],
            "max_items": 10,
        },
    },
    {
        "name": "Daynhauhoc",
        "source_type": "rss",
        "feed_url": "https://daynhauhoc.com/latest.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering"],
        "config": {"max_items": 10, "language": "vi"},
    },
    {
        "name": "Machine Learning Cơ Bản",
        "source_type": "web_index",
        "feed_url": "https://machinelearningcoban.com",
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Dữ liệu"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Data/AI", "Engineering"],
        "config": {
            "link_pattern": r"/\d{4}/\d{2}/\d{2}/",
            "exclude_patterns": [r"/page/", r"/tag/", r"/category/"],
            "max_items": 10,
        },
    },
    # GitHub Trending — early code activity signal (github-trending-connector 2026-05-11)
    {
        "name": "GitHub Trending — All Daily",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "", "since": "daily", "max_items": 25},
    },
    {
        "name": "GitHub Trending — Python Daily",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "python", "since": "daily", "max_items": 25},
    },
    {
        "name": "GitHub Trending — Weekly All",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"language": "", "since": "weekly", "max_items": 25},
    },
    {
        "name": "GitHub Trending — TypeScript Daily",
        "source_type": "github_trending",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Quy trình phần mềm", "Công nghệ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Engineering"],
        "config": {"language": "typescript", "since": "daily", "max_items": 15},
    },
    # HuggingFace org models — 8 China AI labs via public HF API (unblock-coverage 2026-05-11)
    {
        "name": "HF DeepSeek",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "deepseek-ai", "max_items": 10, "min_likes": 5},
    },
    {
        "name": "HF Qwen",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "Qwen", "max_items": 10, "min_likes": 5},
    },
    {
        "name": "HF Zhipu (GLM)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "zai-org", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF 01.AI (Yi)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "01-ai", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF Moonshot (Kimi)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "moonshotai", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF Tencent (Hunyuan)",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "tencent", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF MiniMax",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "MiniMaxAI", "max_items": 8, "min_likes": 5},
    },
    {
        "name": "HF Baichuan",
        "source_type": "huggingface",
        "feed_url": None,
        "trust_tier": "high",
        "topics": ["Trí tuệ nhân tạo"],
        "status": "active",
        "region": "china",
        "target_roles": ["Engineering", "Data/AI"],
        "config": {"org": "baichuan-inc", "max_items": 8, "min_likes": 5},
    },
    # Web index sources — scrape index pages for sites without working RSS
    {
        "name": "Anthropic News",
        "source_type": "web_index",
        "feed_url": "https://www.anthropic.com/news",
        "trust_tier": "very_high",
        "topics": ["Trí tuệ nhân tạo", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "global",
        "target_roles": ["Executive", "Engineering", "Data/AI", "Legal/Compliance"],
        "config": {
            "link_pattern": r"/news/[^/]+$",
            "exclude_patterns": [r"/news/?$", r"/news/category/", r"/news/tag/"],
            "max_items": 10,
        },
    },
    {
        "name": "200lab Blog",
        "source_type": "web_index",
        "feed_url": "https://200lab.io/blog",
        "trust_tier": "high",
        "topics": ["Công nghệ", "Quy trình phần mềm"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering", "DevOps"],
        "config": {
            "link_pattern": r"/blog/[a-z0-9-]+$",
            "exclude_patterns": [r"/blog/author/", r"/blog/tag/", r"/blog/category/", r"/blog/?$"],
            "max_items": 10,
        },
    },
    # Playwright sources — JavaScript-rendered SPA sites without RSS
    {
        "name": "VietTimes Công nghệ",
        "source_type": "rss",
        "feed_url": "https://viettimes.vn/rss/khoa-hoc-cong-nghe-109.rss",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering", "Data/AI", "Product"],
        "config": {"max_items": 15, "language": "vi"},
    },
    {
        "name": "ICTNews Công nghệ",
        "source_type": "playwright",
        "feed_url": "https://ictnews.vn/cntt-vien-thong",
        "trust_tier": "medium",
        "topics": ["Công nghệ", "Trí tuệ nhân tạo", "Pháp lý/Tuân thủ"],
        "status": "active",
        "region": "vietnam",
        "target_roles": ["Engineering", "Data/AI", "Executive"],
        "config": {
            "link_selector": "a",
            "link_pattern": r"/[^/?#]+-\d+\.html$",
            "max_items": 10,
        },
    },
    # MLOpsVN Blog — disabled: /blog returns 404 as of 2026-05-12
    # {
    #     "name": "MLOpsVN Blog",
    #     "source_type": "playwright",
    #     "feed_url": "https://mlops.vn/blog",
    #     "status": "inactive",
    # },
]


async def seed() -> None:
    """Insert seed sources if they don't already exist."""
    async with async_session_maker() as session:
        for data in INITIAL_SOURCES:
            result = await session.execute(
                select(Source).where(Source.name == data["name"])
            )
            existing = result.scalar_one_or_none()

            if existing:
                logger.info("Source already exists: %s - skipping", data["name"])
                continue

            source = Source(**data)
            session.add(source)
            await session.commit()
            logger.info("Created source: %s (id=%s)", source.name, source.id)

    logger.info("Seed complete.")


if __name__ == "__main__":
    asyncio.run(seed())
